id: A148959D9
title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth Deity
  White Jambhala'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:34:37.149922
  last_modified_at: 2022-02-28 22:34:37.149925
