id: A148959D9
title: Prayer to Drukpa Kunley
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:34:37.148686
  last_modified_at: 2022-02-28 22:34:37.148690
