id: A148959D9
title: Windhorse Practice of Tārā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:34:37.151733
  last_modified_at: 2022-02-28 22:34:37.151768
